sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t uptospace/rpi3-python .
# push image
- >
  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  docker tag uptospace/rpi3-python uptospace/rpi3-python:3.5.5
  docker push uptospace/rpi3-python:3.5.5
  docker push uptospace/rpi3-python
  